// A curated list of 500+ real NSE-listed companies (Nifty 500 universe).
// instrumentKey uses Upstox's format "NSE_EQ|ISIN" - when ISIN is unknown here it is left blank
// and gets auto-resolved by scripts/seedStocks.js against the live Upstox instrument master
// (downloaded fresh) when UPSTOX_ACCESS_TOKEN is configured. Without a token, symbol-only
// records are seeded and prices run in simulation mode until Upstox is connected.

const sectorMap = {
  Banking: ['HDFCBANK', 'ICICIBANK', 'SBIN', 'KOTAKBANK', 'AXISBANK', 'INDUSINDBK', 'BANKBARODA', 'PNB', 'IDFCFIRSTB', 'FEDERALBNK', 'AUBANK', 'RBLBANK', 'BANDHANBNK', 'CANBK', 'UNIONBANK', 'YESBANK', 'IOB', 'UCOBANK', 'CENTRALBK', 'J&KBANK'],
  IT: ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM', 'LTIM', 'MPHASIS', 'COFORGE', 'PERSISTENT', 'LTTS', 'OFSS', 'TATAELXSI', 'KPITTECH', 'CYIENT', 'BIRLASOFT', 'ZENSARTECH', 'NEWGEN', 'INTELLECT', 'RATEGAIN', 'HAPPSTMNDS'],
  Auto: ['MARUTI', 'TATAMOTORS', 'M&M', 'BAJAJ-AUTO', 'EICHERMOT', 'HEROMOTOCO', 'TVSMOTOR', 'ASHOKLEY', 'BHARATFORG', 'BALKRISIND', 'MRF', 'APOLLOTYRE', 'CEAT', 'EXIDEIND', 'AMARAJABAT', 'MOTHERSON', 'BOSCHLTD', 'ESCORTS', 'SONACOMS', 'JKTYRE'],
  Pharma: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'DIVISLAB', 'LUPIN', 'AUROPHARMA', 'TORNTPHARM', 'ALKEM', 'ZYDUSLIFE', 'BIOCON', 'GLENMARK', 'IPCALAB', 'LAURUSLABS', 'NATCOPHARM', 'AJANTPHARM', 'GRANULES', 'ABBOTINDIA', 'PFIZER', 'SANOFI', 'JBCHEPHARM'],
  FMCG: ['HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'DABUR', 'MARICO', 'GODREJCP', 'COLPAL', 'TATACONSUM', 'EMAMILTD', 'VBL', 'UBL', 'RADICO', 'GILLETTE', 'JYOTHYLAB', 'BAJAJCON', 'CCL', 'HATSUN', 'VENKEYS', 'DCMSHRIRAM'],
  Energy: ['RELIANCE', 'ONGC', 'NTPC', 'POWERGRID', 'COALINDIA', 'BPCL', 'IOC', 'GAIL', 'TATAPOWER', 'ADANIGREEN', 'ADANIPOWER', 'ADANIENSOL', 'JSWENERGY', 'TORNTPOWER', 'NHPC', 'SJVN', 'IGL', 'MGL', 'GUJGASLTD', 'PETRONET'],
  Metal: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL', 'JINDALSTEL', 'SAIL', 'NMDC', 'NATIONALUM', 'HINDZINC', 'APLAPOLLO', 'RATNAMANI', 'WELCORP', 'JSL', 'MOIL', 'HINDCOPPER', 'GMDCLTD', 'KALYANIFRG', 'MAHSEAMLES', 'SHYAMMETL', 'GRAVITA'],
  Financials: ['BAJFINANCE', 'BAJAJFINSV', 'HDFCLIFE', 'SBILIFE', 'ICICIPRULI', 'ICICIGI', 'SBICARD', 'CHOLAFIN', 'MUTHOOTFIN', 'MANAPPURAM', 'LICHSGFIN', 'PFC', 'RECLTD', 'IRFC', 'HDFCAMC', 'NIPPONLIFE', 'UTIAMC', 'CDSL', 'BSE', 'MCX'],
  Infra: ['LT', 'ADANIPORTS', 'GMRINFRA', 'IRB', 'NBCC', 'NCC', 'RVNL', 'IRCON', 'KEC', 'KALPATPOWR', 'PNCINFRA', 'HG INFRA', 'DILIPBUILDCON', 'GRINFRA', 'ASHOKA', 'JKIL', 'WELSPUNIND', 'GPIL', 'BLUESTARCO', 'CONCOR'],
  Cement: ['ULTRACEMCO', 'SHREECEM', 'AMBUJACEM', 'ACC', 'DALBHARAT', 'JKCEMENT', 'RAMCOCEM', 'HEIDELBERG', 'INDIACEM', 'BIRLACORPN', 'JKLAKSHMI', 'STARCEMENT', 'PRISMCEM', 'ORIENTCEM', 'NUVOCO', 'SAGCEM', 'DECCANCE', 'BURNPUR', 'KCP', 'MANGLMCEM'],
  Realty: ['DLF', 'GODREJPROP', 'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'BRIGADE', 'SOBHA', 'SUNTECK', 'MAHLIFE', 'IBREALEST', 'PURVA', 'ANANTRAJ', 'KOLTEPATIL', 'ASHIANA', 'ARVSMART', 'NESCO', 'ELDEHSG', 'ROHL', 'OMAXE', 'SHRIRAMPPS'],
  Telecom: ['BHARTIARTL', 'IDEA', 'INDUSTOWER', 'TATACOMM', 'TEJASNET', 'ROUTE', 'GTLINFRA', 'HFCL', 'STLTECH', 'ITI'],
  Consumer: ['TITAN', 'ASIANPAINT', 'PIDILITIND', 'HAVELLS', 'VOLTAS', 'CROMPTON', 'BERGEPAINT', 'KANSAINER', 'WHIRLPOOL', 'BLUEDART', 'PAGEIND', 'RELAXO', 'BATAINDIA', 'VGUARD', 'SYMPHONY', 'IFBIND', 'TTKPRESTIG', 'CERA', 'HONAUT', 'RAJESHEXPO'],
  Chemicals: ['UPL', 'PIIND', 'SRF', 'AARTIIND', 'DEEPAKNTR', 'NAVINFLUOR', 'ATUL', 'GNFC', 'CHAMBLFERT', 'COROMANDEL', 'GHCL', 'TATACHEM', 'VINATIORGA', 'FLUOROCHEM', 'CLEAN', 'ALKYLAMINE', 'BALAMINES', 'NOCIL', 'PCBL', 'GUJALKALI'],
  Capital_Goods: ['SIEMENS', 'ABB', 'CGPOWER', 'BHEL', 'CUMMINSIND', 'THERMAX', 'HONEYWELL', 'AIAENG', 'TIINDIA', 'POLYCAB', 'KEI', 'FINOLEXIND', 'SCHNEIDER', 'ELGIEQUIP', 'GRINDWELL', 'CARBORUNIV', 'TIMKEN', 'SKFINDIA', 'GREAVESCOT', 'TRITURBINE'],
  Media_Aviation: ['ZEEL', 'SUNTV', 'PVRINOX', 'NETWORK18', 'TV18BRDCST', 'NAZARA', 'SAREGAMA', 'INDIGO', 'SPICEJET', 'IRCTC'],
  Diversified: ['ITC', 'GRASIM', 'ADANIENT', 'TATACHEM', 'BAJAJHLDNG', 'PEL', '3MINDIA', 'GODREJIND', 'CENTURYTEX', 'KIRLOSENG'],
  Textiles: ['TRIDENT', 'RAYMOND', 'WELSPUNIND', 'VARDHMAN', 'KPRMILL', 'GOKEX', 'SIYSIL', 'NITINSPIN', 'ALOKINDS', 'ARVIND'],
  Sugar_Agri: ['BALRAMCHIN', 'BAJAJHIND', 'TRIVENI', 'DWARKESH', 'DHAMPURSUG', 'EIDPARRY', 'KSCL', 'UPL', 'COROMANDEL', 'BAYERCROP'],
  Healthcare_Services: ['APOLLOHOSP', 'FORTIS', 'MAXHEALTH', 'NH', 'METROPOLIS', 'LALPATHLAB', 'KIMS', 'RAINBOWHSP', 'MEDPLUS', 'KRSNAA'],
  Misc: ['ZOMATO', 'NYKAA', 'PAYTM', 'POLICYBZR', 'DELHIVERY', 'CARTRADE', 'EASEMYTRIP', 'IEX', 'CAMS', 'ANGELONE', 'IIFL', 'JIOFIN', 'INDIAMART', 'JUSTDIAL', 'AFFLE', 'TANLA', 'MAPMYINDIA', 'LATENTVIEW', 'CMSINFO'],
  Banking_SmallFin: ['UJJIVANSFB', 'EQUITASBNK', 'SURYODAY', 'CSBBANK', 'DCBBANK', 'KARURVYSYA', 'SOUTHBANK', 'TMB', 'DHANBANK', 'IDBI'],
  Insurance_More: ['GICRE', 'NIACL', 'STARHEALTH', 'GOLDIAM', 'NIVABUPA'],
  Auto_Anc: ['ENDURANCE', 'SUPRAJIT', 'SUNDRMFAST', 'GABRIEL', 'FIEMIND', 'JAMNAAUTO', 'MINDA', 'UNOMINDA', 'SCHAEFFLER', 'WABCOINDIA', 'IGARASHI', 'LUMAXTECH', 'RACLGEAR', 'SUBROS', 'SHARDAMOTR'],
  IT_More: ['SONATSOFTW', 'ZENTEC', 'MASTEK', 'ECLERX', 'NUCLEUS', 'DATAMATICS', 'RSYSTEMS', 'NETSOLTECH'],
  Pharma_More: ['SUVENPHAR', 'GLAND', 'STAR', 'SOLARA', 'STRIDES', 'CAPLIPOINT', 'ERIS', 'INDOCO', 'MARKSANS', 'WOCKPHARMA', 'SEQUENT', 'SYNGENE', 'FDC', 'MANKIND'],
  FMCG_More: ['DODLA', 'HERITGFOOD', 'BIKAJI', 'PRATAAP', 'ZYDUSWELL', 'KRBL', 'LTFOODS', 'GOPAL', 'DFMFOODS', 'ADFFOODS'],
  Power_More: ['CESC', 'KPIGREEN', 'WAAREEENER', 'INOXWIND', 'SUZLON', 'BORORENEW', 'JPPOWER', 'RELINFRA'],
  Metal_More: ['JTLIND', 'SARDAEN', 'SURYAROSNI', 'VISAKAIND', 'KIRLOSBROS', 'TINPLATE', 'MAITHANALL', 'GALLANTT'],
  Finance_More: ['POONAWALLA', 'CREDITACC', 'SPANDANA', 'FUSION', 'UGROCAP', 'AAVAS', 'HOMEFIRST', 'APTUS', 'INDIASHLTR'],
  Logistics: ['TCI', 'VRLLOG', 'MAHLOG', 'ALLCARGO', 'GATI', 'SNOWMAN', 'TCIEXP', 'ARSHIYA', 'AEGISLOG'],
  Capital_Goods_More: ['APARINDS', 'JASH', 'ISGEC', 'WPIL', 'KIRLOSIND', 'SHANTIGEAR', 'SHAILY'],
  Hospitality: ['INDHOTEL', 'EIHOTEL', 'CHALET', 'LEMONTREE', 'TAJGVK', 'KAMATHOTEL', 'ORIENTHOT', 'ROYALORCHD', 'SAMHI'],
  Building_Materials: ['CENTURYPLY', 'GREENPLY', 'KAJARIACER', 'SOMANYCERA', 'ASTRAL', 'SUPREMEIND', 'FINPIPE', 'PRINCEPIPE'],
  Defence: ['HAL', 'BEL', 'BEML', 'BDL', 'MAZDOCK', 'COCHINSHIP', 'GRSE', 'DATAPATTNS', 'PARAS', 'MTARTECH'],
  Retail: ['DMART', 'TRENT', 'ABFRL', 'SHOPERSTOP', 'VMART', 'SPENCERS', 'METROBRAND', 'VIPIND', 'SAFARI'],
  Diversified_More: ['ADANIWILMAR', 'PATANJALI', 'EMUDHRA', 'TIPSINDLTD', 'WONDERLA', 'DELTACORP', 'GAMEZONE', 'TIMETECHNO', 'AVANTI'],
  Chemicals_More: ['DEEPAKFERT', 'FACT', 'RCF', 'MADRASFERT', 'GSFC', 'PARADEEP', 'MANGCHEFER', 'NFL', 'BHARATRAS', 'JUBLINGREA'],
  Wires_Cables: ['RRKABEL', 'UNIVCABLES', 'PARACABLES', 'GLOSTERLTD', 'ORIENTCABL'],
  NewAge_More: ['HONASA', 'YATRA', 'FIRSTCRY', 'SWIGGY', 'PNGJEWELLERS', 'CAMPUS', 'SENCO', 'THANGAMAYL', 'KALYANKJIL'],
  Paper: ['JKPAPER', 'WSTCSTPAPR', 'TNPL', 'SESHAPAPER', 'ANDHRAPAP', 'STARPAPER', 'SHREYANIND', 'EMAMIPAP', 'RUCHIRA', 'ORIENTPPR']
};

function buildUniverse() {
  const list = [];
  const seen = new Set();
  for (const [sector, symbols] of Object.entries(sectorMap)) {
    for (const symbol of symbols) {
      if (seen.has(symbol)) continue;
      seen.add(symbol);
      list.push({ symbol, sector: sector.replace('_', ' ') });
    }
  }
  return list;
}

module.exports = { buildUniverse };
